# This is the manifest file for building CrysFML with fpm
# It is better to comment the part corresponding to executables in order to construct
# the library totally independent of the programs using it.
#
name = "CrysFML08"
version = "0.1.0"
license = "LGPL"
author = "Juan Rodriguez-Carvajal, Javier Gonzalez-Platas, Nebil A. Katcho"
maintainer = "jrc@ill.eu"
copyright = "Copyright 2022, Juan Rodriguez-Carvajal, Javier Gonzalez-Platas, Nebil A. Katcho"

[library]
source-dir = "Src"
include-dir = "Src"

[build]
auto-executables = false
auto-tests = false
auto-examples = false

[install]
library = true



#
# The lines above are enough for building the library using the scripts make_CrysFML_fpm.bat/make_CrysFML_fpm.sh
#
#==============================================================================================
# WARNING! For building the executables uncomment the lines below once the library is installed
#==============================================================================================
#
# Some executables from Testing
#

#[[executable]]
#executable = [
#  { name = "cryscalcon",     source-dir = "Testing/Cryst_calculator_console", main = "cryscalc_con.f90"},
#  { name = "hkl_gen",        source-dir = "Testing/hkl_gen",                  main = "hkl_gen.f90"},
#  { name = "Formal_Charges", source-dir = "Testing/BondStr/FormalCharges",    main = "Formal_Charges.f90"},
#  { name = "Bond_Str",       source-dir = "Testing/BondStr/Src",              main = "Bond_Str.f90"}
#]
#[[executable]]
#name="cryscalcon"
#source-dir="Testing/Cryst_calculator_console"
#main="cryscalc_con.f90"
#
#[[executable]]
#name="hkl_gen"
#source-dir="Testing/hkl_gen"
#main="hkl_gen.f90"
#
#[[executable]]
#name="Formal_Charges"
#source-dir="Testing/BondStr/FormalCharges"
#main="Formal_Charges.f90"
#
#[[executable]]
#name="Bond_Str"
#source-dir="Testing/BondStr/Src"
#main="Bond_Str.f90"
#
#[[executable]]
#name="Similar"
#source-dir="Testing/SimilarityTransformations"
#main="Similar.f90"
#
#[[executable]]
#name="space_group_info"
#source-dir="Testing/SpaceGroups"
#main="space_group_info.f90"
#
#[[executable]]
#name="subgroups"
#source-dir="Testing/SpaceGroups"
#main="subgroups.f90"
#
##
## Structure factors
##
#
#[[executable]]
#name="Calc_mSfac"
#source-dir="Testing/StructureFactors"
#main="Calc_mSfac.f90"
#
#[[executable]]
#name="Calc_Sfac"
#source-dir="Testing/StructureFactors"
#main="Calc_Sfac.f90"
#
##
## Structures_GlobalOptimization
##
#[[executable]]
#name="GLOpSAnn"
#source-dir="Testing/Structures_GlobalOptimization/Src"
#main="GLOpSAnn.f90"
#
##
## Metric
##
#[[executable]]
#name="Get_Conv_Cell"
#source-dir="Testing/Metrics"
#main="Get_Conv_Cell.f90"
#
#[[executable]]
#name="search_cellrelations"
#source-dir="Testing/Metrics"
#main="search_cellrelations.f90"
#
##
## Magnetic examples, polarimetry
##
#[[executable]]
#name="MagPolar3D"
#source-dir="Testing/Magnetism"
#main="MagPolar3D.f90"
#
#[[executable]]
#name="magref"
#source-dir="Testing/Magnetism"
#main="magref.f90"
#
#################### Warning! ifx in mode release is unable to compile Schwinger: hn = real(hkl%ref(i)%h,kind=cp)
##[[executable]]
##name="Schwinger"
##source-dir="Testing/Magnetism"
##main="Schwinger.f90"
#
#[[executable]]
#name="Moment"
#source-dir="Testing/Magnetism/Moment"
#main="moment.f90"
#
#[[executable]]
#name="MagOptim"
#source-dir="Testing/Magnetism/MagOptim_v4"
#main="MagOptim.f90"
#
##
## Magnetic package Simbo, EnerMag, Phase_Diagram and MC_Mag
##
#[[executable]]
#name="Simbo"
#source-dir="Testing/Simbo-Enermag"
#main="Simbo.f90"
#
#[[executable]]
#name="EnerMag"
#source-dir="Testing/Simbo-Enermag"
#main="EnerMag.f90"
#
#[[executable]]
#name="Phase_Diagram"
#source-dir="Testing/Simbo-Enermag"
#main="Phase_Diagram.f90"
#
#[[executable]]
#name="MC_Mag"
#source-dir="Testing/Simbo-Enermag/MC_Mag"
#main="mc_mag.f90"
#
##
## Faults Program
##
#[[executable]]
#name="DIFFaX2FAULTS"
#source-dir="Testing/Faults/DIFFaX2FAULTS"
#main="DIFFaX2FAULTS.f90"
#
#[[executable]]
#name="Faults"
#source-dir="Testing/Faults/Src"
#main="Faults.f90"
#
##
## Powder Patterns
##
#[[executable]]
#name="Simple_calc_Mag_powder"
#source-dir="Testing/PowderPattern"
#main="Simple_calc_Mag_powder.f90"
#
#[[executable]]
#name="Calc_Powder"
#source-dir="Testing/PowderPattern"
#main="calc_powder.f90"
#
#[[executable]]
#name="Simple_Calc_Powder"
#source-dir="Testing/PowderPattern"
#main="Simple_calc_powder.f90"
#
#[[executable]]
#name="Correct_Cells"
#source-dir="Testing/PowderPattern"
#main="corr_cells.f90"
#
#[[executable]]
#name="Laue_Powder"
#source-dir="Testing/PowderPattern"
#main="Laue_powder.f90"
#
##
## Single X-tal diffractometry
##
#
#[[executable]]
#name="d10_flat_cone"
#source-dir="Testing/SXtal_Diffractometry"
#main="d10_flat_cone.f90"
#
#[[executable]]
#name="get_UB_from2ref"
#source-dir="Testing/SXtal_Diffractometry"
#main="get_UB_from2ref.f90"
